const ssaQs = {
    'Next Generation SOC Qs': [
        'Defining mission, vision, KPIs',
        'Defining stakeholders',
        'Defining compliance and regulatory requirements',
        'Defining policies and procedures policies and procedures',
        'Establishing a steering committee',
        'Gathering steering committee inputs',
        'Defining business use cases',
        'Defining environment baseline',
        'Utilizing predictive threat and anomaly identification',
        'Outsourcing infrastructure, and/or data storage',
        'Utilizing self-supervised artificial intelligence, self-learning system',
        'Defining internal and external threats',
        'Utilizing integrated threat intel feeds',
        'Utilizing big data architecture',
        'Utilizing real-time behavioral analytics',
        'Utilizing contextual enrichment',
        'Utilizing packaged content services',
        'Automating incident response'],
    'SOC KPI Qs': [
        'Tracking dwell time',
        'Tracking the number of incidents',
        'Tracking number of event escalations day / 30 days',
        'Tracking number of false positives',
        'Tracking number of true positives',
        'Tracking mean time to detect / respond / contain / eradicate',
        'Tracking number of incidents closed in 24 hours',
        'Tracking the number of incidents due to unpatched vulnerabilities',
        'Tracking risk against digital crown jewels',
        'Tracking amount of outages caused by incidents',
        'Tracking recurring incidents / infections',
        'Tracking number of impacted customers',
        'Tracking physical security anomalies',
        'Tracking number of IOCs collected',
        'Tracking data feed latency',
        'Tracking data feed ldrops',
        'Tracking Agents health(log forwarder, AV, EDR etc)',
        'Tracking security device availability',
        'Tracking security platform availability',
        'Tracking MITRE coverage',
        'Tracking kill chain coverage',
        'Tracking percent of devices covered',
        'Tracking the number of detections in Dev',
        'Tracking the number of detections in dcom',
        'Tracking the number of detections in Prod',
        'Tracking number of times a detection fired',
        'Tracking median run time per query / detection',
        'Tracking time spent per case',
        'Tracking top  firing detections',
        'Tracking top sources of confirmed incidents',
        'Tracking SLA - time spent waiting on other teams',
        'Tracking expected cost',
        'Tracking detection efficacy',
        'Tracking expected true positives',
        'Tracking detection latency',
        'Tracking average security incident resolution',
        'Tracking average security incident age',
        'Tracking closed incidents per analyst',
        'Tracking worked incidents per analyst',
        'Tracking security incidents backlog',
        'Tracking closed security incidents per month over the last 3 months',
        'Tracking security incident age',
        'Tracking security incident resolution time',
        'Tracking cost per incident',
        'Tracking losses per incident',
    ],
    'Utilization & Normalization Qs': [
        'Completion of onboarding and normalizing firewall logs',
        'Utilizing g firewall logs',

        'Completion of onboarding and normalizing next-gen firewall logs',
        'Utilizing next-gen firewall logs',

        'Completion of onboarding and normalizing IPS/IDS logs',
        'Utilizing IPS/IDS logs',

        'Completion of onboarding and normalizing windows security and event logs',
        'Utilizing windows security and event logs',

        'Completion of onboarding and normalizing linux os and security logs',
        'Utilizing linux os and security logs',

        'Completion of onboarding and normalizing  active directory, azure ad logs',
        'Utilizing active directory, azure ad logs',

        'Completion of onboarding and normalizing sso and/or saml logs',
        'Utilizing sso and/or saml logs',

        'Completion of onboarding and normalizing av/malware logs',
        'Utilizing  av/malware logs',

        'Completion of onboarding and normalizing vulnerability scanner logs',
        'Utilizing vulnerability scanner logs',

        'Completion of onboarding and normalizing server EDR logs',
        'Utilizing server EDR logs',

        'Completion of onboarding and normalizing EDR client logs',
        'Utilizing EDR client logs',

        'Completion of onboarding and normalizing vpn logs',
        'Utilizing vpn logs',

        'Completion of onboarding and normalizing DNS logs',
        'Utilizing DNS logs',

        'Completion of onboarding and normalizing DHCP logs',
        'Utilizing DHCP logs',

        'Completion of onboarding and normalizing email filter logs',
        'Utilizing email filter logs',

        'Completion of onboarding and normalizing email logs (to include the full body of emails for support of insider threat)',
        'Utilizing email logs (to include the full body of emails for support of insider threat)',

        'Completion of onboarding and normalizing PowerShell/CLI logs',
        'Utilizing PowerShell/CLI logs',

        'Completion of onboarding and normalizing file audit logs',
        'Utilizing file audit logs',

        'Completion of onboarding and normalizing sysmon logs',
        'Utilizing sysmon logs',

        'Completion of onboarding and normalizing DLP logs',
        'Utilizing  DLP logs',

        'Completion of onboarding and normalizing application logs',
        'Utilizing  application logs',

        'Completion of onboarding and normalizing NAC logs',
        'Utilizing NAC logs',

        'Completion of onboarding and normalizing web server',
        'Utilizing web server',

        'Completion of onboarding and normalizing web application logs',
        'Utilizing web application logs',

        'Completion of onboarding and normalizing physical security logs (badge reader data, security cameras, etc)',
        'Utilizing  physical security logs(badge reader data, security cameras, etc)',

        'Completion of onboarding and normalizing printer/copier logs',
        'Utilizing  printer/copier logs',

        'Completion of onboarding and normalizing chat logs(slack, teams, google chat, etc In support of insider threat)',
        'Utilizing  chat logs(slack, teams, google chat, etc In support of insider threat)',

        'Completion of onboarding and normalizing database logs',
        'Completion of utilizing database logs',

        'Completion of onboarding and normalizing database query logs',
        'Completion utilizing  database query logs',

        'Completion of onboarding and normalizing industry-specific system logs',
        'Utilizing  industry-specific system logs',

        'Completion of onboarding and normalizing honeypot logs',
        'Utilizing honeypot logs',
        'What is the percentage of utilizing  honeypot logs'],
    'Use Case Qs': [
        'Defining the scope and use cases for next-gen firewall logs',
        'Defining the scope and use cases for IPS/IDS logs',
        'Defining the scope and use cases for windows security and event logs',
        'Defining the scope and use cases for linux os and security logs',
        'Defining the scope and use cases for active directory, azure ad logs',
        'Defining the scope and use cases for sso and/or saml logs',
        'Defining the scope and use cases for av/malware logs',
        'Defining the scope and use cases for vulnerability scanner logs',
        'Defining the scope and use cases for server EDR logs',
        'Defining the scope and use cases for EDR client logs',
        'Defining the scope and use cases for vpn logs',
        'Defining the scope and use cases for DNS logs',
        'Defining the scope and use cases for DHCP logs',
        'Defining the scope and use cases for email filter logs',
        'Defining the scope and use cases for (to include the full body of emails for support of insider threat)',
        'Defining the scope and use cases for PowerShell/CLI logs',
        'Defining the scope and use cases for file audit logs',
        'Defining the scope and use cases for sysmon logs',
        'Defining the scope and use cases for DLP logs',
        'Defining the scope and use cases for application logs',
        'Defining the scope and use cases for NAC logs',
        'Defining the scope and use cases for web server',
        'Defining the scope and use cases for web application logs',
        'Defining the scope and use cases for physical security logs(badge reader data, security cameras, etc)',
        'Defining the scope and use cases for printer/copier logs',
        'Defining the scope and use cases for chat logs(slack, teams, google chat, etc In support of insider threat)',
        'Defining the scope and use cases for database logs',
        'Defining the scope and use cases for database query logs',
        'Defining the scope and use cases for industry-specific system logs',
        'Defining the scope and use cases for honeypot logs',
    ],
    'Enrichment Qs': [
        'Assets List',
        'Users Lists',
        'VIP/C-Level accounts list',
        'Administrative accounts',
        'Service/Non-human accounts list',
        'Default Accounts',
        'Compliance withTraining list',
        'Background checks data',
        'Criminal history data',
        'Termination Notice List',
        'Resignation notice list',
        'known Organizational Units',
        'Competitors domain list',
        '1M domain list',
        'Low performance review data',
        'Resignation data',
        'Force reduction data',
        'Know/Allowed/Denied web-agent',
        'Know/Allowed/Denied File Extensions',
        'Known/Allowed/Denied application protocols',
        'Known/Allowed/Denied network ports',
        'Known/Allowed/Denied processes',
        'Known/Allowed/Denied services',
        'Network subnets list',
        'Known/Allowed Fax destination numbers',
        'Good countries List',
        'Honeypots list',
        'Vulnerability Scanners',
        'Headquarters locations',
        'Offices locations',
        'Threat Intelegance'],
    'Insider Threat Profile Qs': [
        'Completion of defining insider threat programs',
        'Completion of response plans/workbooks for identified ITP scenarios',
        'Analyze user behavior by detecting anomalies against a baseline (UBA)',
        'Monitoring social media anomalies',
        'Monitoring foreign contacts',
        'Monitoring foreign travel',
        'Monitoring physical access anomalies',
        'Monitoring access levels',
        'Monitoring large outbound email traffic',
        'Monitoring emails with attachments',
        'Monitoring printers',
        'Monitoring fax',
        'Monitoring removable media',
        'Monitoring antivirus/antimalware alerts',
        'Monitoring downloads',
        'Monitoring access denials',
        'Monitoring compliance with training ',
        'Monitoring expense violations',
        'Monitoring time entry violations',
        'Monitoring notice of resignation',
        'Monitoring notice of termination',
        'Monitoring warnings',
        'Monitoring criminal history',
        'Monitoring background checks'],
    'Threat Hunting Qs': [
        'Establishing threat hunting goals',
        'Current coverage of threat hunting goals',
        'Hirining personnel dedicated to threat hunting',
        'Formulating a threat hunting hypothesis',
        'Acquiring specialized datasets and tools',
        'Threat hunting training',
        'SOC members who can develop needed cybersecurity scripts',
        'Utlzing full packet capture',
        'Utlzing windows registry keys',
        'Utlzing system memory analysis',
        'Ability to scale threat hunting program'],
    'Vulnerability Managment Qs': [
        'Well Defined and maintained assets risk tolerance',
        'Well Defined and maintained Application risk tolerance',
        'OS Scanning',
        'Hardware Scanning',
        'Applications Scanning',
        'Identifying and prioritizing risk relative to the environment',
        'Action tasks on devices to eliminate security risks',
        'Effective collaboration between IT & security teams',
        'Deploying os & third-party patches',
        'Deploying windows 10 feature updates',
        'Sharing, communicating vulnerability with other teams',
        'Remediating vulnerability'],
    'Threat Intelligence Qs': [
        'Defining and maintain a list of known good Geographical locations',
        'Ability to collect IOCs from internal events',
        'Ability to curate threat feed from internal events',
        'Integrating with multiple threat 3d party threat feeds',
        'Ability to utlize 3dpart and/or internal IOC in correlation searches',
        'Defining templates for conducting root cause analysis',
        'Conducting root cause analysis'],
    'Data Masking Qs': [
        'Define data masking scope',
        'Crating pattern-based detections',
        'Ensuring that PII or other sensitive data is obfuscated or access restricted',
        'Ensuring that sensitive data that has been identified',
        'Ensuring that sensitive data is appropriately monitored and dashboards are present to visualize',
        'Ensuring that critical security incidents have the appropriate response plans',
        'Ensuring that fraudulent transactions identified'],
    'SOAR Qs': [
        'Creating a response and process automation with workflow integrations via SOAR',
        'Creating response plans within SOAR using workbooks',
        'Creating event management workflows using playbooks within SOAR',
        'Creating event escalation workflows using playbooks within SOAR',
        'Creating actions, as required, that use automation workflows within SOAR to automate mundane tasks such as port or IP blocking, etc',
        'Creating a process to identify false positives from the SOC analysts that can be flag alerts for additional tuning',
        'Identify complex investigations and create associated playbooks within SOAR to elevate those events to Tier 3 analysts ',
        'What is the percentage of security analysts who can effectively write Python, PowerShell, Go scripts'],
    'Process Qs': [
        'Define enterprise log collection process',
        'Apply log collection process',
        'Audit and enhance log collection process',
        'Define incident response process',
        'Apply incident response process',
        'Audit and enhance incident response process',
        'Define event escalation process',
        'Apply event escalation process',
        'Audit and enhance event escalation process',
        'Define event assignment / resolution process',
        'Apply event assignment / resolution process',
        'Audit and enhance event assignment / resolution process',
        'Define case management process',
        'Apply case management process',
        'Audit and enhance case management process',
        'Define content lifecycle management process',
        'Apply content lifecycle management process',
        'Audit and enhance content lifecycle management process',
        'Define vulnerability management process',
        'Apply vulnerability management process',
        'Audit and enhance vulnerability management process',
        'Define patching process',
        'Apply Define patching process',
        'Audit and enhance Define patching process',
        'Define threat hunting process',
        'Apply threat hunting process',
        'Audit and enhance threat hunting process',
        'Define threat modeling process',
        'Apply threat modeling process',
        'Audit and enhance threat modeling process',
        'Define endpoint monitoring process',
        'Apply endpoint monitoring process',
        'Audit and enhance endpoint monitoring process'],
    'SOC Staff Qs': [
        'Define number of needed soc analysts',
        'Define number of needed security architects',
        'Define number of needed security engineers',
        'Define number of needed threat analysts',
        'Define number of needed reverse malware engineers',
        'Define number of needed data scientist',
        'Define number of needed incident responder',
        'Fully hire the needed soc analysts',
        'Fully hire the needed security architects',
        'Fully hire the needed security engineers',
        'Fully hire the needed threat analysts',
        'Fully hire the needed reverse malware engineers',
        'Fully hire the needed data scientist',
        'Fully hire the needed incident responder',
        'Run 24 / 7 Security Operation'],
    'Training Accredidation Qs': [
        'Define SOC Analyst(s) Training Program',
        'Define Security Architect(s) Training Program',
        'Define Security Engineer(s) Training Program',
        'Define Threat Analyst(s) Training Program',
        'Define Reverse Malware Engineer(s) Training Program',
        'Define Data Scientist(s) Training Program',
        'Define Incident Responder(s) Handler(s)  Training Program',
        'Define Securonix training for SOC Analyst(s)',
        'Complete Securonix training for Security Architect(s)',
        'Complete Securonix training for Security Engineer(s)',
        'Complete Securonix training for Threat Analyst(s)',
        'Complete Securonix training for Reverse Malware Engineer(s)',
        'Complete Securonix training for Data Scientist(s)',
        'Complete Securonix training for Incident Responder(s) Handler(s)'],
    'DFIR Qs': [
        'Using enterprise Forensic Lab',
        'Define full list of all needed software and hardwares',
        'Having needed software',
        'Having needed hard',
        'Getting needed training',
        'Ability to generate reports utilizing data from the Securonix and other platforms',
        'Developing Threat Intel',
        'Feed SIEM Team with inisder threat intel',
        'Ability to do Windows forensics',
        'Ability to do Linux forensics',
        'Ability to do Unix forensics',
        'Ability to do Mac forensics',
        'Ability to do Memory forensics',
        'Ability to do Mobile forensics',
        'Ability to do Network forensics'],
    'Fraud Prevention Qs': [
        '(Define) fraud Risk within the organization',
        '(Use) Create detections  that map to fraud risks',
        '(Use) Testing transactional data for potential fraud and build apporpriate use cases',
        '(Use) Creating response plans / workbooks for identified Fraud scenarios',
        ' (Use) Use case management for identified fraud risks'],
    'Red, Blue & Purple Teams Qs': [
        'Define clear red team tctivities and contrubutino to the SOC maturity',
        'Define clear blue team tctivities and contrubutino to the SOC maturity',
        'Define clear purple team tctivities and contrubutino to the SOC maturity',
        'red team shares results of breach attempts in order to verify effectiveness of controls',
        'purple team adversary simulations verify existing controls and identify potential gaps in detections',
        'red / purple team shares methods of successful breaches in order to build new detections / on - board new data / create new response procedures',
        'blue team incorporates lessons learned into detection engineering',
        'using knowledge mangement system to track gaps in detections and improvements, while ensuring improvements/new detections follow a lifecycle process'],
    'Security Mangement Qs': [
        'Defining data governance between the various entities of the secuirty operations teams',
        'Utilizing a RACI to track ownership of the various data sources and programs within the SOC',
        'Utilizing a knowledge management system like JIRA/Confluence/MS Teams to track all Secuirty Operations Document',
        'Ensuring that use cases are aligned to business/organizational risk from previous risk impact assessments'],
    'Risk Qs': [
        'Create risk impact assessments Template',
        'Use risk impact assessments Template',
        'Update risk impact assessments Template',
        'Regularly conducting risk impact assessments',
        'Creage risk register',
        'Maintain a risk register and document all known risks in the environment in this centralized document',
        'Creating threat profiles for crown jewels',
        'Running risk assessments if a critical asset / user / object is changed in order to effectively determine the new risk',
        'Incorporating risk ratings into all security detections to provide higher fidelity and more actionable alerts',
        'Continuously prioritizing risks with the environment and are made available to the platform',
        'Utilizing machine learning and artificial intelligence to build baselines and perform anomaly detections',
        'Ensuring that all IR plans are aligned against the identified risks in the risk register'],
    'On Call Qs': [
        'Documenting and establishing call lists with Business contacts',
        'Documenting and establishing  call lists with IT contacts',
        'Documenting and establishing call lists with third - party contacts',
        'Documenting and establishing  call lists with vendor contacts',
        'Completion of defining  mean time to acknowledge per each category',
        'Efficiently and efficiently assigning On - Call Scheduling',
        'Efficiently and efficiently changing On - Call Scheduling '],
    'Physical Security Qs': [
        'Security guard requirment',
        'Surveilance system requirement and archives',
        'Entry point restrictions',
        'Building reinforcement - protect against physical attack',
        'Complete periodic security assessment',
        'Entry log book',
        'Document inventory changes',
        'Inventory facilities']
}

export default ssaQs;